In [4]:
import numpy as np

In [5]:
# 1. Creating NumPy Arrays
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", array_1d)

1D Array:
 [1 2 3 4 5]


In [6]:
# Create a 2D array (matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array (Matrix):\n", array_2d)


2D Array (Matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Create an array of zeros
zeros_array = np.zeros((3, 3))
print("\nArray of Zeros:\n", zeros_array)


Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Create an array of ones
ones_array = np.ones((2, 4))
print("\nArray of Ones:\n", ones_array)


Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
# Create an identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix:\n", identity_matrix)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:

# Create an array with a range of values
range_array = np.arange(0, 10, 2)
print("\nArray with Range of Values:\n", range_array)



Array with Range of Values:
 [0 2 4 6 8]


In [11]:
# Create an array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)
print("\nArray with Evenly Spaced Values:\n", linspace_array)


Array with Evenly Spaced Values:
 [0.   0.25 0.5  0.75 1.  ]


In [12]:
# 2. Array Operations
# Element-wise addition
addition = array_1d + 10
print("\nElement-wise Addition:\n", addition)


Element-wise Addition:
 [11 12 13 14 15]


In [13]:
# Element-wise multiplication
multiplication = array_1d * 2
print("\nElement-wise Multiplication:\n", multiplication)


Element-wise Multiplication:
 [ 2  4  6  8 10]


In [14]:
# Matrix multiplication
matrix_multiplication = np.dot(array_2d, array_2d)
print("\nMatrix Multiplication:\n", matrix_multiplication)


Matrix Multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [15]:
# Transpose of a matrix
transpose_matrix = array_2d.T
print("\nTranspose of Matrix:\n", transpose_matrix)


Transpose of Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
# 3. Array Indexing and Slicing
# Accessing elements
print("\nElement at index 2 in 1D array:", array_1d[2])
print("Element at row 1, column 2 in 2D array:", array_2d[1, 2])


Element at index 2 in 1D array: 3
Element at row 1, column 2 in 2D array: 6


In [17]:
# Slicing
print("\nSlice of 1D array (from index 1 to 3):", array_1d[1:4])
print("Slice of 2D array (first two rows, all columns):\n", array_2d[:2, :])


Slice of 1D array (from index 1 to 3): [2 3 4]
Slice of 2D array (first two rows, all columns):
 [[1 2 3]
 [4 5 6]]


In [18]:
# 4. Array Aggregations
# Sum of all elements
sum_all = np.sum(array_2d)
print("\nSum of all elements in 2D array:", sum_all)


Sum of all elements in 2D array: 45


In [19]:
# Mean of all elements
mean_all = np.mean(array_2d)
print("Mean of all elements in 2D array:", mean_all)

Mean of all elements in 2D array: 5.0


In [20]:
# Maximum element
max_element = np.max(array_2d)
print("Maximum element in 2D array:", max_element)

Maximum element in 2D array: 9


In [21]:
# Minimum element
min_element = np.min(array_2d)
print("Minimum element in 2D array:", min_element)

Minimum element in 2D array: 1


In [22]:
# 5. Reshaping Arrays
# Reshape a 1D array to a 2D array
reshaped_array = array_1d.reshape(5, 1)
print("\nReshaped 1D array to 2D array:\n", reshaped_array)


Reshaped 1D array to 2D array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [23]:
# Flatten a 2D array to a 1D array
flattened_array = array_2d.flatten()
print("\nFlattened 2D array to 1D array:\n", flattened_array)


Flattened 2D array to 1D array:
 [1 2 3 4 5 6 7 8 9]


In [24]:
# 6. Random Number Generation
# Generate random numbers from a uniform distribution
random_uniform = np.random.rand(3, 3)
print("\nRandom numbers from a uniform distribution:\n", random_uniform)


Random numbers from a uniform distribution:
 [[0.8104674  0.5645179  0.9352909 ]
 [0.17861114 0.88949367 0.34364989]
 [0.12242294 0.3432634  0.9883867 ]]


In [25]:
# Generate random numbers from a normal distribution
random_normal = np.random.randn(3, 3)
print("\nRandom numbers from a normal distribution:\n", random_normal)


Random numbers from a normal distribution:
 [[ 1.11692311 -0.33228704  1.54577151]
 [-0.22027297  0.31229809  1.16258219]
 [-1.46551832 -0.76138076 -0.04409807]]


In [26]:
# Generate random integers
random_integers = np.random.randint(0, 10, (3, 3))
print("\nRandom integers between 0 and 10:\n", random_integers)


Random integers between 0 and 10:
 [[4 9 7]
 [1 1 1]
 [4 8 0]]


In [27]:
# 7. Advanced Operations
# Broadcasting
broadcasted_array = array_1d + np.array([10, 20, 30, 40, 50])
print("\nBroadcasting Example:\n", broadcasted_array)


Broadcasting Example:
 [11 22 33 44 55]


In [28]:
# Vectorized operations
vectorized_sqrt = np.sqrt(array_1d)
print("\nSquare root of each element in 1D array:\n", vectorized_sqrt)


Square root of each element in 1D array:
 [1.         1.41421356 1.73205081 2.         2.23606798]


In [29]:
# Conditional operations
conditional_array = np.where(array_1d > 3, array_1d, 0)
print("\nConditional Operation (elements > 3):\n", conditional_array)


Conditional Operation (elements > 3):
 [0 0 0 4 5]


In [30]:
# 8. Saving and Loading Arrays
# Save an array to a file
np.save('saved_array.npy', array_2d)

In [31]:
# Load an array from a file
loaded_array = np.load('saved_array.npy')
print("\nLoaded Array from File:\n", loaded_array)


Loaded Array from File:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
